export const NavigationStacks = {
  DASHBOARDSTACK: 'DASHBOARDSTACK',
  WATCHSTACK: 'WATCHSTACK',
  MEDIASTACK: 'MEDIASTACK',
  MORESTACK: 'MORESTACK',
  TABSTACK: 'TABSTACK',
};

export const ScreenNameEnum = {
  DASHBOARD: 'DASHBOARD',
  WATACH: 'WATACH',
  MEDIA: 'MEDIA',
  MORE: 'MORE',
  TRAILOR: 'TRAILOR',
  CINEMATICKET: 'CINEMATICKET',
};
